# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logoproposal',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the logo proposal. Can be the philosophy or story behind the design. Should be fit within three Tweets (less than 420 chars).', max_length=420),
        ),
    ]
