# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 19:08
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations
import reviews.models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20160925_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='approach',
            field=reviews.models.ReviewScoreField(blank=True, help_text='The use of color, shape, pattern, and pictures. Is it captivating and easy on your eyes?', null=True, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='environment',
            field=reviews.models.ReviewScoreField(blank=True, default=1, help_text='Nothing. Give 1 to everyone.', null=True, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='innovation',
            field=reviews.models.ReviewScoreField(blank=True, help_text='Original but not at the expense of the message. Unique but not odd. Creative but not ugly.', null=True, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='investigator',
            field=reviews.models.ReviewScoreField(blank=True, help_text='NIH evaluates investigators to gauge the chance of getting the proposed products. We are evaluating the finished products. So, what is the point?!', null=True, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='overall_impact',
            field=reviews.models.ReviewScoreField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='significance',
            field=reviews.models.ReviewScoreField(blank=True, help_text='Symbolize key characteristics of the lab. Inspiration. Simple but meaningful.', null=True, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(1)]),
        ),
    ]
